theme = "apollo"
taxonomies = [{ name = "tags" }]
base_url="https://lucassimpson0213.github.io/notes-blog"
build_search_index = true
[extra]
toc = true
stylesheets = ["giallo.css"]

mathjax_dollar_inline_enable = true
mathjax = true
theme = "auto"
socials = [
  { name = "twitter", url = "https://twitter.com/not_matthias", icon = "twitter" },
  { name = "github", url = "https://github.com/lucassimpson0213/", icon = "github" },
]
menu = [
{name = "/root", url = "/", weight= 1},
   { name = "/posts", url = "/posts", weight = 1 },
   { name = "Documentation", url = "/repos/", weight = 1 },
]


[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown.highlighting]
error_on_missing_language = true
style = "class"
theme = "gruvbox-dark-hard"

